### ISSUE TITLE
Parsing error, tutorial will not start up.

### ISSUE THREAD

**Issue by prrose** [swimos/to-do-list#1]
Running Java 9.0.4

$ ./gradlew.bat run
> Task :compileJava UP-TO-DATE
> Task :processResources UP-TO-DATE
> Task :classes UP-TO-DATE
> Task :jar UP-TO-DATE

> Task :run
Todo app started
Todo app started
swim.codec.ParserError@46b2e162
error: unexpected ' '
 --> :1:17
  |
1 | C:/Users/Prairie Rose/Downloads/to-do-list-master/server
  |                 ^
        at swim.codec/swim.codec.Parser.error(Parser.java:231)
        at swim.uri/swim.uri.UriParser.parseAbsoluteString(UriParser.java:84)
        at swim.uri/swim.uri.Uri.parse(Uri.java:563)
        at swim.server/swim.server.SwimHttpServer.<init>(SwimHttpServer.java:52)
        at swim.server/swim.server.ServerPlaneHttpService.createServer(ServerPlaneHttpService.java:32)
        at swim.io.http/swim.io.http.HttpSocketService.createSocket(HttpSocketService.java:50)
        at swim.io/swim.io.TcpService.doAccept(TcpService.java:115)
        at swim.io/swim.io.StationTransport.doAccept(Station.java:453)
        at swim.io/swim.io.StationThread.doAccept(Station.java:1062)
        at swim.io/swim.io.StationThread.select(Station.java:988)
        at swim.io/swim.io.StationThread.run(Station.java:865)
error: unexpected ' '
 --> :1:17
  |
1 | C:/Users/Prairie Rose/Downloads/to-do-list-master/server
  |                 ^
        at swim.codec/swim.codec.Parser.error(Parser.java:231)
        at swim.uri/swim.uri.UriParser.parseAbsoluteString(UriParser.java:84)
        at swim.uri/swim.uri.Uri.parse(Uri.java:563)
        at swim.server/swim.server.SwimHttpServer.<init>(SwimHttpServer.java:52)
        at swim.server/swim.server.ServerPlaneHttpService.createServer(ServerPlaneHttpService.java:32)
        at swim.io.http/swim.io.http.HttpSocketService.createSocket(HttpSocketService.java:50)
        at swim.io/swim.io.TcpService.doAccept(TcpService.java:115)
        at swim.io/swim.io.StationTransport.doAccept(Station.java:453)
        at swim.io/swim.io.StationThread.doAccept(Station.java:1062)
        at swim.io/swim.io.StationThread.select(Station.java:988)
        at swim.io/swim.io.StationThread.run(Station.java:865)

**Comment by ajay-gov** [comment]
Issue is with the [tutorial](https://github.com/swimos/tutorial) repo.

**Comment by prrose** [comment]
Edited to correct text.  I had errors in both repos, and copied the wrong one.  Issue is with todolist.
